// examples/lit/pokemon-catalog/src/components/pokemon-image/pokemon-image.component.driver.ts
import { CypressLitComponentHelper } from "@shellygo/cypress-test-utils/lit";
import { html } from "lit";
import { PokemonImageComponent } from "./pokemon-image.component";

export class PokemonImageComponentDriver {
  private helper = new CypressHelper("data-hook");
  private litComponentHelper = new CypressLitComponentHelper();
  private props = {
    pokemonIndex: 0
  };
  beforeAndAfter = () => {
    this.helper.beforeAndAfter();
  };

  given = {
    pokemonIndex: (value: number) => {
      this.props.pokemonIndex = value;
    },
    mockImageResponse: (fileName: string) =>
      this.helper.given.interceptAndMockResponse({
        url: "**/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/**",
        response: { fixture: fileName }
      }),
    missingImage: () =>
      this.helper.given.interceptAndMockResponse({
        url: "**/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/**",
        response: { headers: 404 }
      })
  };

  when = {
    render: (element: PokemonImageComponent) => {
      this.litComponentHelper.when.mount(
        element,
        html`<pokemon-image pokemonIndex="${this.props.pokemonIndex}"></pokemon-image>`
      );
    }
  };

  get = {
    pokemonImage: () => this.helper.get.elementByTestId("pokemon-image"),
    fallBackImage: () => this.helper.get.elementByTestId("pokemon-fallback-image"),
    pictureSrc: () => this.helper.get.elementsAttribute("pokemon-image", "src"),
    fallbackPictureSrc: () => this.helper.get.elementsAttribute("pokemon-fallback-image", "src")
  };
}

// examples/angular/pokemon-catalog/src/app/components/pokemon-image/pokemon-image.component.driver.ts
import type { Type } from "@angular/core";
import { CypressAngularComponentHelper } from "@shellygo/cypress-test-utils/angular";
import { MountConfig } from "cypress/angular";
import type { PokemonImageComponent } from "./pokemon-image.component";

export class PokemonImageComponentDriver {
  private helper = new CypressHelper("data-hook");
  private angularComponentHelper = new CypressAngularComponentHelper<PokemonImageComponent>();
  private componentProperties: Partial<PokemonImageComponent> = {};

  beforeAndAfter = () => {
    this.helper.beforeAndAfter();
  };

  given = {
    pokemonIndex: (value: number) => (this.componentProperties.pokemonIndex = value),
    mockImageResponse: (fileName: string) =>
      this.helper.given.interceptAndMockResponse({
        url: "**/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/**",
        response: { fixture: fileName }
      }),
    missingImage: () =>
      this.helper.given.interceptAndMockResponse({
        url: "**/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/**",
        response: { headers: 404 }
      })
  };

  when = {
    render: (type: Type<PokemonImageComponent>, config: MountConfig<PokemonImageComponent>) => {
      this.angularComponentHelper.when.mount(type, config, {
        ...this.componentProperties
      });
    }
  };

  get = {
    pokemonImage: () => this.helper.get.elementByTestId("pokemon-image"),
    fallBackImage: () => this.helper.get.elementByTestId("pokemon-fallback-image"),
    pictureSrc: () => this.helper.get.elementsAttribute("pokemon-image", "src"),
    fallbackPictureSrc: () => this.helper.get.elementsAttribute("pokemon-fallback-image", "src")
  };
}
