// examples/react/pokemon-catalog/src/components/pokemon-image/pokemon-image.component.tsx
import { SyntheticEvent, useState } from "react";
import "./pokemon-image.scss";

export interface IProps {
  pokemonIndex: number;
}

export const PokemonImageComponent = (props: IProps) => {
  const { pokemonIndex } = props;
  const [showFallbackImage, setShowFallbackImage] = useState(false);

  const onImageError = (event: SyntheticEvent<HTMLImageElement, Event>) => {
    setShowFallbackImage(true);
  };

  const getPokemonImage = () =>
    `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/${pokemonIndex}.gif`;

  const getFallbackImage = () =>
    `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemonIndex}.png`;

  return (
    <div>
      {showFallbackImage ? (
        <img
          data-cy="pokemon-fallback-image"
          src={getFallbackImage()}
          alt="pokemon"
        />
      ) : (
        <img
          data-cy="pokemon-image"
          src={getPokemonImage()}
          className="pokemon"
          alt="pokemon"
          onError={onImageError}
        />
      )}
    </div>
  );
};

// examples/angular/pokemon-catalog/src/app/components/pokemon-image/pokemon-image.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "pokemon-image",
  template: `<div *ngIf="pokemonIndex">
    <div>
      <img
        *ngIf="!showFallbackImage"
        class="pokemon"
        data-cy="pokemon-image"
        src="{{ getPokemonImage() }}"
        alt="pokemon"
        (error)="onImageError($event)"
      />
      <img
        *ngIf="showFallbackImage"
        class="pokemon-fallback"
        data-cy="pokemon-fallback-image"
        src="{{ getFallbackImage() }}"
        alt="pokemon"
      />
    </div>
  </div> `,
  styleUrls: ["./pokemon-image.component.scss"]
})

//
export class PokemonImageComponent {
  @Input() pokemonIndex: number = 1;
  showFallbackImage: boolean = false;

  onImageError(event: ErrorEvent) {
    this.showFallbackImage = true;
  }

  getPokemonImage = () => {
    return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/${this.pokemonIndex}.gif`;
  };

  getFallbackImage = () => {
    return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${this.pokemonIndex}.png`;
  };
}

<div *ngIf="pokemonIndex">
  <div>
    <img
      *ngIf="!showFallbackImage"
      class="pokemon"
      data-cy="pokemon-image"
      src="{{ getPokemonImage() }}"
      alt="pokemon"
      (error)="onImageError($event)"
    />
    <img
      *ngIf="showFallbackImage"
      class="pokemon-fallback"
      data-cy="pokemon-fallback-image"
      src="{{ getFallbackImage() }}"
      alt="pokemon"
    />
  </div>
</div>
