// examples/lit/pokemon-catalog/src/components/pokemon-catalog/pokemon-catalog.component.ts
import { PokemonImageComponent } from "@components/pokemon-image/pokemon-image.component";
import { ContextConsumer } from "@lit-labs/context";
import { PokemonList, PokemonService, pokemonServiceContext } from "@services/pokemon.service";
import { LitElement, html } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import styles from "./pokemon-catalog.component.scss";

@customElement("pokemon-catalog")
export class PokemonCatalog extends LitElement {
  @property()
  onPrev?: () => void;

  @property()
  onNext?: () => void;

  @state()
  pokemon!: PokemonList;

  @state()
  getPokemonService!: () => PokemonService;

  private pokemonService;

  static override get styles() {
    return styles;
  }
  constructor() {
    super();
    new PokemonImageComponent();
  }

  override connectedCallback() {
    super.connectedCallback();

    new ContextConsumer(
      this,
      pokemonServiceContext,
      context => {
        this.pokemonService = context.getPokemonService()();
      },
      true
    );
    if (this.pokemonService.getPokemon) this.loadPokemon();
  }

  isNextDisabled = () => !this.pokemon.next || !this.pokemonService;
  isPrevDisabled = () => !this.pokemon.previous || !this.pokemonService;

  loadPokemon = async () => (this.pokemon = await this.pokemonService.getPokemonByOffset());

  loadNext = async () => {
    this.onNext && this.onNext();
    this.pokemon = await this.pokemonService.getPokemon(this.pokemon.next);
  };

  loadPrev = async () => {
    this.pokemon = await this.pokemonService.getPokemon(this.pokemon.previous);
    this.onPrev && this.onPrev();
  };

  getPokemonIndex = () =>
    Number(
      this.pokemon?.results[0].url
        .split("/")
        .filter(element => element)
        .pop()
    );
  getPokemonName = () => this.pokemon?.results[0].name;
  getOffsetFromIndex = (index: string) => (Number(index) - 1).toString();

  fetchPokemonByOffset = async (index: string) => {
    const pokemon = await this.pokemonService?.getPokemonByOffset(this.getOffsetFromIndex(index));
    if (pokemon?.results.length) {
      this.pokemon = pokemon;
    } else {
      alert(`pokemon ${index} not found`);
    }
  };

  protected override render() {
    return !this.pokemon
      ? ""
      : html`
          <div class="catalog">
            <pokemon-image pokemonIndex="${this.getPokemonIndex()}"></pokemon-image>
            <h2 data-hook="pokemon-name">${this.pokemon.results[0].name}</h2>
            <p data-hook="count">${this.getPokemonIndex()} of ${this.pokemon.count}</p>
            <div>
              <button data-hook="prev" @click="${this.loadPrev}" .disabled="${this.isPrevDisabled()}">Prev</button>
              <button data-hook="next" @click="${this.loadNext}" .disabled="${this.isNextDisabled()}">Next</button>
            </div>
          </div>
        `;
  }
}

// examples/react/pokemon-catalog/src/components/pokemon-catalog/pokemon-catalog.component.tsx
import { useCallback, useContext, useEffect, useState } from "react";
import "../../App.scss";
import { IPokemonService, PokemonList, PokemonServiceContext } from "../../services/pokemon.service";
import { PokemonImageComponent } from "../pokemon-image/pokemon-image.component";
export interface IPokemonCatalogComponentsProps {
  onPrev?: () => void;
  onNext?: () => void;
}

export const PokemonCatalogComponent = (props: IPokemonCatalogComponentsProps) => {
  const { onNext, onPrev } = props;
  const [pokemon, setPokemon] = useState<PokemonList>();
  const pokemonService: IPokemonService | undefined = useContext(PokemonServiceContext);
  const fetchNext = async () => {
    if (pokemon && pokemon.next) {
      const nextPokemon = await pokemonService?.getPokemon(pokemon.next);
      setPokemon(nextPokemon);
    }
    onNext && onNext();
  };

  const fetchPrev = async () => {
    if (pokemon && pokemon.previous) {
      const prevPokemon = await pokemonService?.getPokemon(pokemon.previous);
      setPokemon(prevPokemon);
    }
    onPrev && onPrev();
  };

  const fetchByOffset = useCallback(
    async (index: string) => {
      const getOffsetFromIndex = (index: string) => (Number(index) - 1).toString();
      const offset: string = getOffsetFromIndex(index);
      const pokemon = await pokemonService?.getPokemonByOffset(offset);
      if (pokemon?.results.length) {
        setPokemon(pokemon);
      } else {
        alert(`pokemon ${index} not found`);
      }
    },
    [pokemonService]
  );

  const getFirstPokemon = useCallback(async () => fetchByOffset("1"), [fetchByOffset]);
  useEffect(() => {
    getFirstPokemon();
  }, [getFirstPokemon]);

  const getPokemonIndex = () =>
    Number(
      pokemon?.results[0]?.url
        .split("/")
        .filter(element => element)
        .pop() || 0
    );
  const getPokemonName = () => pokemon?.results[0]?.name;

  return (
    <div>
      <header>
        {pokemon && (
          <>
            <PokemonImageComponent pokemonIndex={getPokemonIndex()} />
            <h2 data-hook="pokemon-name">{getPokemonName()}</h2>
            <div data-hook="count">{`${getPokemonIndex()} of ${pokemon.count}`}</div>
            <div>
              <button data-hook="prev" onClick={fetchPrev} disabled={!(pokemon && pokemon.previous)}>
                Prev
              </button>
              <button data-hook="next" onClick={fetchNext} disabled={!(pokemon && pokemon.next)}>
                Next
              </button>
            </div>
          </>
        )}
      </header>
    </div>
  );
};
