// examples/angular/pokemon-catalog/src/app/components/pokemon-catalog/pokemon-catalog.component.ts
import { Component, EventEmitter, Output } from "@angular/core";
import { PokemonList, PokemonService } from "src/app/services/pokemon.service";

@Component({
  selector: "pokemon-catalog",
  template: `<div class="catalog">
    <pokemon-image [pokemonIndex]="getPokemonIndex()"></pokemon-image>
    <h1 *ngIf="pokemon" data-cy="pokemon-name">{{ getPokemonName() }}</h1>

    <p data-cy="count" *ngIf="pokemon">{{ getPokemonIndex() }} of {{ pokemon.count }}</p>
    <div>
      <button data-cy="prev" (click)="fetchPrev()" [disabled]="prevDisabled()">Prev</button>
      <button data-cy="next" (click)="fetchNext()" [disabled]="nextDisabled()">Next</button>
    </div>
    <div>
      <br />
    </div>
  </div> `,
  styleUrls: ["./pokemon-catalog.component.scss"]
})

//
export class PokemonCatalogComponent {
  pokemon: PokemonList = {
    count: 0,
    next: null,
    previous: null,
    results: []
  };
  @Output() onNext: EventEmitter<any> = new EventEmitter();
  @Output() onPrev: EventEmitter<any> = new EventEmitter();

  constructor(private readonly pokemonService: PokemonService) {}

  ngOnInit() {
    this.getFirstPokemon();
  }

  private getFirstPokemon = async () => {
    this.pokemon = await this.pokemonService.getPokemonByOffset();
  };

  getPokemonName = () => this.pokemon?.results[0]?.name;

  nextDisabled = () => !(this.pokemon && this.pokemon.next);
  prevDisabled = () => !(this.pokemon && this.pokemon.previous);

  fetchNext = async () => {
    if (this.pokemon && this.pokemon.next) {
      this.pokemon = await this.pokemonService.getPokemon(this.pokemon.next);
    }
    this.onNext.emit();
  };

  fetchPrev = async () => {
    if (this.pokemon && this.pokemon.previous) {
      this.pokemon = await this.pokemonService.getPokemon(this.pokemon.previous);
    }
    this.onPrev.emit();
  };

  getPokemonIndex = (): number =>
    Number(
      this.pokemon?.results[0]?.url
        .split("/")
        .filter(element => element)
        .pop()
    );

  fetchPokemonByOffset = async (index: string) => {
    const pokemon = await this.pokemonService.getPokemonByOffset(`${Number(index) - 1}`);
    if (pokemon?.results.length) {
      this.pokemon = pokemon;
    } else {
      alert(`pokemon ${index} not found`);
    }
  };
}

<div class="catalog">
  <pokemon-image [pokemonIndex]="getPokemonIndex()"></pokemon-image>
  <h1 *ngIf="pokemon" data-cy="pokemon-name">{{ getPokemonName() }}</h1>

  <p data-cy="count" *ngIf="pokemon">
    {{ getPokemonIndex() }} of {{ pokemon.count }}
  </p>
  <div>
    <button data-cy="prev" (click)="fetchPrev()" [disabled]="prevDisabled()">
      Prev
    </button>
    <button data-cy="next" (click)="fetchNext()" [disabled]="nextDisabled()">
      Next
    </button>
  </div>
  <pokemon-go (selectedPokemon)="selectPokemon($event)"></pokemon-go>
</div>

// examples/react/pokemon-catalog/src/components/pokemon-catalog/pokemon-catalog.component.tsx
import { useContext, useEffect, useState } from "react";
import "../../App.scss";
import {
  PokemonList,
  PokemonService,
  PokemonServiceContext
} from "../../services/pokemon.service";
import { PokemonImageComponent } from "../pokemon-image/pokemon-image.component";
export interface IPokemonCatalogComponentsProps {
  onPrev?: () => void;
  onNext?: () => void;
}

export const PokemonCatalogComponent = (
  props: IPokemonCatalogComponentsProps
) => {
  const { onNext, onPrev } = props;
  const [pokemon, setPokemon] = useState<PokemonList>();
  const pokemonService: PokemonService | undefined = useContext(
    PokemonServiceContext
  );
  const fetchNext = async () => {
    if (pokemon && pokemon.next) {
      const nextPokemon = await pokemonService?.getPokemon(pokemon.next);
      setPokemonIfValid(nextPokemon);
    }
    onNext && onNext();
  };

  const setPokemonIfValid = (pokemon?: PokemonList) => {
    if (pokemon?.results.length) {
      setPokemon(pokemon);
    } else {
      alert(`pokemon not found`);
    }
  };
  const fetchPrev = async () => {
    if (pokemon && pokemon.previous) {
      const prevPokemon = await pokemonService?.getPokemon(pokemon.previous);
      setPokemonIfValid(prevPokemon);
    }
    onPrev && onPrev();
  };

  const getOffsetFromIndex = (index: string) => (Number(index) - 1).toString();
  const fetchByOffset = async (index: string = "1") => {
    const offset: string = getOffsetFromIndex(index);
    const pokemon = await pokemonService?.getPokemonByOffset(offset);
    setPokemonIfValid(pokemon);
  };

  useEffect(() => {
    const getFirstPokemon = async () => fetchByOffset();
    getFirstPokemon();
  }, []);

  const getPokemonIndex = () =>
    Number(
      pokemon?.results[0]?.url
        .split("/")
        .filter(element => element)
        .pop() || 0
    );
  const getPokemonName = () => pokemon?.results[0]?.name;

  return (
    <div>
      <header>
        {pokemon && (
          <>
            <PokemonImageComponent pokemonIndex={getPokemonIndex()} />
            <h2 data-cy="pokemon-name">{getPokemonName()}</h2>
            <div data-cy="count">{`${getPokemonIndex()} of ${
              pokemon.count
            }`}</div>
            <div>
              <button
                data-cy="prev"
                onClick={fetchPrev}
                disabled={!(pokemon && pokemon.previous)}
              >
                Prev
              </button>
              <button
                data-cy="next"
                onClick={fetchNext}
                disabled={!(pokemon && pokemon.next)}
              >
                Next
              </button>
            </div>
          </>
        )}
      </header>
    </div>
  );
};
