// examples/lit/pokemon-catalog/src/components/pokemon-image/pokemon-image.component.ts
import { LitElement, html } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import styles from "./pokemon-image.component.scss";

@customElement("pokemon-image")
export class PokemonImageComponent extends LitElement {
  @property({ type: Number })
  pokemonIndex!: number;

  @state()
  showFallbackImage = false;

  static override get styles() {
    return styles;
  }

  onImageError = event => {
    this.showFallbackImage = true;
  };

  getPokemonImage = () =>
    `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/${this.pokemonIndex}.gif`;

  getFallbackImage = () =>
    `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${this.pokemonIndex}.png`;

  protected override render() {
    return html`
      <div>
        ${this.showFallbackImage
          ? html` <img
              data-hook="pokemon-fallback-image"
              src="${this.getFallbackImage()}"
              class="pokemon-fallback"
              alt="pokemon"
            />`
          : html`<img
              data-hook="pokemon-image"
              src="${this.getPokemonImage()}"
              class="pokemon"
              alt="pokemon"
              @error="${this.onImageError}"
            />`}
      </div>
    `;
  }
}

// examples/react/pokemon-catalog/src/components/pokemon-image/pokemon-image.component.tsx
import { SyntheticEvent, useEffect, useState } from "react";
import "./pokemon-image.scss";

export interface IProps {
  pokemonIndex: number;
}

export const PokemonImageComponent = (props: IProps) => {
  const { pokemonIndex } = props;
  const [showFallbackImage, setShowFallbackImage] = useState(false);
  useEffect(() => setShowFallbackImage(false), [pokemonIndex]);

  const onImageError = (event: SyntheticEvent<HTMLImageElement, Event>) => {
    setShowFallbackImage(true);
  };

  const getPokemonImage = () =>
    `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/${pokemonIndex}.gif`;

  const getFallbackImage = () =>
    `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemonIndex}.png`;

  return (
    <div>
      {showFallbackImage ? (
        <img data-hook="pokemon-fallback-image" src={getFallbackImage()} alt="pokemon" />
      ) : (
        <img
          data-hook="pokemon-image"
          src={getPokemonImage()}
          className="pokemon"
          alt="pokemon"
          onError={onImageError}
        />
      )}
    </div>
  );
};
