// examples/lit/pokemon-catalog/src/components/pokemon-go/pokemon-go.component.driver.ts
import { CypressHelper } from "@shellygo/cypress-test-utils";
import { CypressLitComponentHelper } from "@shellygo/cypress-test-utils/lit";
import { html } from "lit";
import { PokemonGoComponent } from "./pokemon-go.component";

export class PokemonGoComponentDriver {
  private helper = new CypressHelper({ defaultDataAttribute: "data-hook" });
  private litComponentHelper = new CypressLitComponentHelper();
  private props = {
    onSubmit: (pokemonIndex: string) => {}
  };
  beforeAndAfter = () => {
    this.helper.beforeAndAfter();
  };

  given = {
    onSubmitSpy: () => {
      this.props.onSubmit = this.helper.given.spyOnObject(this.props, "onSubmit");
    }
  };

  when = {
    render: (element: PokemonGoComponent) => {
      this.litComponentHelper.when.unmount(element);
      this.litComponentHelper.when.mount(element, html`<pokemon-go .onSubmit="${this.props.onSubmit}"></pokemon-go>`);
    },
    typePokemonIndex: (input: string) => this.helper.when.type("pokemon-index", input),
    clickGo: () => this.helper.when.click("go")
  };

  get = {
    onSubmitSpy: () => this.helper.get.spy("onSubmit"),
    pokemonIndexInputValue: () => this.helper.get.inputValue("pokemon-index"),
    goButton: () => this.helper.get.elementByTestId("go")
  };
}

// examples/angular/pokemon-catalog/src/app/components/pokemon-go/pokemon-go.component.driver.ts
import type { Type } from "@angular/core";
import { CypressHelper } from "@shellygo/cypress-test-utils";
import { CypressAngularComponentHelper } from "@shellygo/cypress-test-utils/angular";
import { MountConfig } from "cypress/angular";
import { PokemonGoComponent } from "./pokemon-go.component";

export class PokemonGoComponentDriver {
  private helper = new CypressHelper({ defaultDataAttribute: "data-hook" });
  private angularComponentHelper = new CypressAngularComponentHelper<PokemonGoComponent>();

  private componentProperties: Partial<PokemonGoComponent> = {};

  beforeAndAfter = () => {
    this.helper.beforeAndAfter();
  };

  given = {};

  when = {
    render: (type: Type<PokemonGoComponent>, config: MountConfig<PokemonGoComponent>) => {
      this.angularComponentHelper.when.mount(type, config, {
        ...this.componentProperties
      });
    },
    typePokemonIndex: (value: string) => this.helper.when.type("pokemon-index", value),
    clickGo: () => this.helper.when.click("go")
  };

  get = {
    pokemonIndexInputValue: () => this.helper.get.inputValue("pokemon-index"),
    selectedPokemonSpy: () => this.helper.get.spy("selectedPokemon"),
    goButton: () => this.helper.get.elementByTestId("go")
  };
}
