// examples/react/pokemon-catalog/src/components/pokemon-go/pokemon-go.tsx
import React, { useState } from "react";

export interface IProps {
  onSubmit: (searchedPokemon: string) => void;
}
export const PokemonGoComponent = ({ onSubmit }: IProps) => {
  const [searchedPokemon, setSearchedPokemon] = useState("");
  const [pokemonIndex, setValue] = useState("");

  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const digitsRegex = /^[0-9\b]+$/;
    if (event.target.value === "" || digitsRegex.test(event.target.value)) {
      setSearchedPokemon(event.target.value);
      setValue(event.target.value);
    }
  };

  return (
    <form
      onSubmit={e => {
        e.preventDefault();
        onSubmit(searchedPokemon);
        setValue("");
      }}
    >
      <input
        data-cy="pokemon-index"
        value={pokemonIndex}
        onChange={onChange}
        placeholder="Pokemon"
      />
      <button type="submit" data-cy="go" disabled={pokemonIndex === ""}>
        Go
      </button>
    </form>
  );
};

// examples/angular/pokemon-catalog/src/app/components/pokemon-go/pokemon-go.component.ts
import { Component, EventEmitter, Output } from "@angular/core";

@Component({
  selector: "pokemon-go",
  template: `<form>
    <input
      data-cy="pokemon-index"
      [(ngModel)]="pokemonIndex"
      (keypress)="numericOnly($event)"
      name="pokemon-index"
    />
    <button
      type="submit"
      data-cy="go"
      (click)="onSubmit()"
      (keydown.enter)="onSubmit()"
      [disabled]="pokemonIndex === ''"
    >
      Go
    </button>
  </form>`
})
export class PokemonGoComponent {
  @Output()
  selectedPokemon: EventEmitter<string> = new EventEmitter<string>();

  public pokemonIndex: string = "";

  public onSubmit = () => {
    this.selectedPokemon.emit(this.pokemonIndex);
    this.pokemonIndex = "";
  };

  numericOnly = (event: KeyboardEvent): boolean => {
    if (event.key === "Enter") return true;
    let digitsRegex = /^([0-9])$/;
    let result = digitsRegex.test(event.key);
    return result;
  };
}

<div>
    <input data-cy="search-input" type="number" [(ngModel)]="searchTerm" />
    <button data-cy="go" (click)="onSumbit()">Go</button>
</div>
